version: '2'
services:
  kali:
    image: kalilinux/kali-linux-docker
    volumes:
      - ./data/kali:/app
    command: /app/install.sh
  host1:
    build: ./eg_sshd
    image: ubuntu
    volumes:
      - ./data/host1:/root
    expose:
      - 22
  host2:
    image: httpd:2.4
    volumes:
      - ./data/host2:/usr/local/apache2/htdocs/
    expose:
        - 80
