kali:
  image: kalilinux/kali-linux-docker
  volumes:
    - ./data/kali:/app
  command: /app/install.sh
host1:
  build: ./eg_sshd
  volumes:
    - ./data/host1:/root
  expose:
    - 22
host2:
  image: httpd:2.4
  volumes:
    - ./data/host2:/usr/local/apache2/htdocs/
  ports:
      - "80:80"
  expose:
      - 80
